public class Task1 {
    public static void main(String[] args) {
        int number = 50;
        int solvers = 10;
        int positionX = 200;
        int positionY = 10;
        int timeInHour = 20;
        int countStep;
        int speedX = positionX / timeInHour;
        int year = 1999;
        int month;
        int days;
        int countBooks = 1000;
        int countOldBooks = 784;
        int countNewBooks = countBooks - countOldBooks;
        int estimationStudent;
        int auditoriumInUniversity = 200;
        int apples = 5;
        byte countFlowersInRoom = 3;
        byte pets = 3;
        byte countCat = 2;
        byte countDog = 2;
        byte countParrot = 2;
        byte footCat = 4;
        byte footDog = 4;
        byte footParrot = 2;
        byte footsAllPets = (byte) (footParrot * countParrot + footCat * countCat + footDog * countDog);
        System.out.print(footsAllPets);
        byte apple, orange, banana;
        byte pen, pencil, notebook, eraser;
        short fishNumber = 3;
        short cheeseNumber = 2;
        short lunch = (short) (fishNumber + cheeseNumber);
        short areas = 30;
        short letters = 200;
        short countHatsInShop = 5000;
        short countCaps = 1000;
        short countPeakedCap = 2000;
        short countHelmet = 995;
        short countHandkerchief = (short) (countHatsInShop - countCaps - countPeakedCap - countHelmet);
        short notebooks, magazines, newspapers;
        short x = Short.parseShort("100");
        short photosInTelephone = 3000;
        short musicInPlaylist = 678;
        short ship = 2;
        double area = 52;
        int peopleInHouse = 3;
        double areaOnEveryone = area / peopleInHouse;
        double periodicity = 344.97;
        double temperatureDay1 = 23.4;
        double temperatureDay2 = 25.9;
        double temperatureDay3 = 27.0;
        double temperatureDay4 = 30.1;
        double temperatureDay5 = 29.4;
        double temperatureDay6 = 33.8;
        double temperatureDay7 = 34.0;
        double temperatureMiddle = (temperatureDay1 + temperatureDay2 + temperatureDay3 + temperatureDay4 + temperatureDay5 + temperatureDay6 + temperatureDay7) / 7;
        double heightSteps = 13.5;
        double heightStairs = 202.5;
        countStep = (int)(heightStairs/heightSteps);
        double balDistance;
        long night = 101L;
        long distance = 112656000L;
        long sunEarth = 149597871L;
        long lettersInHogvarts = 1100000L;
        long keys = 120000000L;
        long n = Long.parseLong("100");
        long distanceToMoscow,distanceUlyanovsk, distanceToSamara;
        long populationMoscow, populationLondon, populationMinsk;
        long speedStar;
        long treasInForest;
        long deepOcean;
        float aw = Float.parseFloat("19.95");
        float tugrik = 11.6F;
        float catsEatMass;
        float temperatureInRoom = 26.7F;
        float temperatureMy = 36.6F;
        float weightMyBag = 1.2F;
        float radiusCoin = 2.1F;
        float heightTree = 30.88F;
        float speedCar = 44.8F;
        float songFavoriteLine = 3.36F;
        float sleepTime = 8.7F;
        float longRoom, widthRoom, heightRoom;
        boolean checkAnswer1 = true;
        boolean checkAnswer2 = false;
        boolean checkAnswer3 = false;
        boolean checkAnswer4 = true;
        boolean checkAnswer5 = true;
        boolean checkAnswer6 = true;
        boolean checkAnswer7 = true;
        boolean checkAnswer8 = true;
        boolean checkAnswer9 = true;
        boolean checkAnswer10 = true;
        boolean checkAnswer11 = true;
        boolean checkAnswer12 = false;
        boolean cabinetIsEmpty = false;
        boolean nightNow = false;
        boolean dayNow = true;
        char sumb = 32;
        char word = 'r';
        char empty = ' ';
        char ch3 = 116;
        char word1, word2, word3;
        char newS1 = 65;
        char newS2 = 66;
        char newS3 = 67;
        char newS4 = 68;
        char newS5 = 69;
        char newS6 = 70;
        char newS7;
        newS7 = 22;
        char favorite = 'S';
    }
}
